on:
  release:
    types: [published]

name: Deploy Rocket Plugin on Dev
jobs:
  deploy:
    name: Deploy Rocket Plugin on Dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run composer
        run: composer install --no-scripts --no-dev
  
      - name: Zip Folder
        run: zip -r /tmp/__wp-rocket__${{ GITHUB_REF }}.zip .

      - name: Upload by sFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_PLUGIN_HOST }}
          username: ${{ secrets.DEPLOY_PLUGIN_USER }}
          source: "/tmp/__wp-rocket__${{ GITHUB_REF }}.zip"
          target: "/var/www/wp-rocket.me/api/wp-rocket/versioning"
          key: ${{ secrets.DEPLOY_PLUGIN_SSH_KEY }}
